---
abstract: 'Pragma to allow comments in qw()'
author:
  - 'Eric Brine <ikegami@adaelis.com>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3614
  Software::License::CC0_1_0: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: feature-qw_comments
provides:
  feature::qw_comments:
    file: lib/feature/qw_comments.pm
    version: v1.10.0
requires:
  XSLoader: 0
  perl: 5.014
  version: 0
resources:
  license: http://creativecommons.org/publicdomain/zero/1.0/
version: v1.10.0
